env:
  browser: true
  commonjs: true
  es6: true
extends: 'eslint:recommended'
parserOptions:
  sourceType: module
rules:
  array-bracket-spacing:
    - error
    - never
  block-scoped-var: error
  comma-dangle:
    - error
    - never
  comma-spacing: error
  comma-style:
    - error
    - last
  curly:
    - error
    - all
  indent:
    - error
    - 2
  object-curly-spacing:
    - error
    - never
  quotes:
    - error
    - single
  semi:
    - error
    - always
  semi-spacing:
    - error
    - 
      before: false
      after: true
  space-before-blocks:
    - error
    - always
  space-before-function-paren:
    - error
    - 
      anonymous: always
      named: never
  space-in-parens:
    - error
    - never
  space-infix-ops: error
  space-unary-ops:
    - error
    - 
      words: true
      nonwords: false
  spaced-comment:
    - off
  strict: error
